# Generated by Django 2.2.28 on 2023-04-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
